services:
  - type: web
    name: bus-arrival-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py bus_arrival:app
    envVars:
      - key: LTA_API_KEY
        sync: false
      - key: LTA_URL
        value: https://datamall2.mytransport.sg/ltaodataservice/v3/BusArrival
        sync: false
    plan: free
    region: oregon
